@startuml MapLogicState
state "MapLogicState" as Labyrinth_MapLogicState {
  state "Idle" as Labyrinth_MapLogicState_Idle
}

Labyrinth_MapLogicState_Idle --> Labyrinth_MapLogicState_Idle : PlayerEnteredLabyrinth
@enduml