@startuml GameLogicState
state "GameLogicState" as Labyrinth_GameLogicState {
  state "Battle" as Labyrinth_GameLogicState_Battle
  state "Labyrinth" as Labyrinth_GameLogicState_Labyrinth
  state "MainMenu" as Labyrinth_GameLogicState_MainMenu
  state "Town" as Labyrinth_GameLogicState_Town
}

Labyrinth_GameLogicState --> Labyrinth_GameLogicState : SetMovementSettings
Labyrinth_GameLogicState_Battle --> Labyrinth_GameLogicState_Labyrinth : EnterLabyrinth
Labyrinth_GameLogicState_Battle --> Labyrinth_GameLogicState_MainMenu : EnterMainMenu
Labyrinth_GameLogicState_Battle --> Labyrinth_GameLogicState_Town : EnterTown
Labyrinth_GameLogicState_Labyrinth --> Labyrinth_GameLogicState_Battle : EnterBattle
Labyrinth_GameLogicState_Labyrinth --> Labyrinth_GameLogicState_MainMenu : EnterMainMenu
Labyrinth_GameLogicState_Labyrinth --> Labyrinth_GameLogicState_Town : EnterTown
Labyrinth_GameLogicState_MainMenu --> Labyrinth_GameLogicState_Battle : EnterBattle
Labyrinth_GameLogicState_MainMenu --> Labyrinth_GameLogicState_Labyrinth : EnterLabyrinth
Labyrinth_GameLogicState_MainMenu --> Labyrinth_GameLogicState_Town : EnterTown
Labyrinth_GameLogicState_Town --> Labyrinth_GameLogicState_Battle : EnterBattle
Labyrinth_GameLogicState_Town --> Labyrinth_GameLogicState_Labyrinth : EnterLabyrinth
Labyrinth_GameLogicState_Town --> Labyrinth_GameLogicState_MainMenu : EnterMainMenu

Labyrinth_GameLogicState : OnSetMovementSettings → MovementSettingsChanged
Labyrinth_GameLogicState_Battle : OnEnter → EnteredBattle
Labyrinth_GameLogicState_Labyrinth : OnEnter → EnteredLabyrinth, MaxFpsRequested
Labyrinth_GameLogicState_MainMenu : OnEnter → EnteredMainMenu
Labyrinth_GameLogicState_Town : OnEnter → EnteredTown
@enduml