@startuml MapMovementLogicState
state "MapMovementLogicState" as Labyrinth_MapMovementLogicState {
  state "Disabled" as Labyrinth_MapMovementLogicState_Disabled
  state "Idle" as Labyrinth_MapMovementLogicState_Idle
  state "MoveCooldown" as Labyrinth_MapMovementLogicState_MoveCooldown
  state "Moving" as Labyrinth_MapMovementLogicState_Moving
  state "Turning" as Labyrinth_MapMovementLogicState_Turning
}

Labyrinth_MapMovementLogicState --> Labyrinth_MapMovementLogicState : SettingsLoaded
Labyrinth_MapMovementLogicState_Disabled --> Labyrinth_MapMovementLogicState_Idle : Enable
Labyrinth_MapMovementLogicState_Idle --> Labyrinth_MapMovementLogicState_Disabled : Disable
Labyrinth_MapMovementLogicState_Idle --> Labyrinth_MapMovementLogicState_Idle : RelativeMoveRequested
Labyrinth_MapMovementLogicState_Idle --> Labyrinth_MapMovementLogicState_Idle : TurnRequested
Labyrinth_MapMovementLogicState_Idle --> Labyrinth_MapMovementLogicState_Turning : TurnRequested
Labyrinth_MapMovementLogicState_MoveCooldown --> Labyrinth_MapMovementLogicState_Disabled : CooldownFinished
Labyrinth_MapMovementLogicState_MoveCooldown --> Labyrinth_MapMovementLogicState_Idle : CooldownFinished
Labyrinth_MapMovementLogicState_MoveCooldown --> Labyrinth_MapMovementLogicState_MoveCooldown : Disable
Labyrinth_MapMovementLogicState_Moving --> Labyrinth_MapMovementLogicState_MoveCooldown : MoveFinished
Labyrinth_MapMovementLogicState_Moving --> Labyrinth_MapMovementLogicState_Moving : Disable
Labyrinth_MapMovementLogicState_Turning --> Labyrinth_MapMovementLogicState_MoveCooldown : TurnFinished
Labyrinth_MapMovementLogicState_Turning --> Labyrinth_MapMovementLogicState_Turning : Disable

Labyrinth_MapMovementLogicState_Idle : OnTurnRequested → TurnStarted
Labyrinth_MapMovementLogicState_Idle : TryStartMove() → MoveBlocked, MoveStarted
Labyrinth_MapMovementLogicState_Idle : TryStartMovePreservingFacing() → MoveBlocked, MoveStarted
Labyrinth_MapMovementLogicState_MoveCooldown : OnEnter → CooldownStarted
Labyrinth_MapMovementLogicState_Moving : OnMoveFinished → MoveFinished
Labyrinth_MapMovementLogicState_Turning : OnTurnFinished → TurnFinished
@enduml