@startuml BattleLogicState
state "BattleLogicState" as Labyrinth_BattleLogicState {
  state "AwaitingCuePlayback" as Labyrinth_BattleLogicState_AwaitingCuePlayback
  state "Completed" as Labyrinth_BattleLogicState_Completed
  state "Disabled" as Labyrinth_BattleLogicState_Disabled
  state "ResolvingTurn" as Labyrinth_BattleLogicState_ResolvingTurn
  state "SelectingCommands" as Labyrinth_BattleLogicState_SelectingCommands
}

Labyrinth_BattleLogicState_AwaitingCuePlayback --> Labyrinth_BattleLogicState_ResolvingTurn : CuePlaybackFinished
Labyrinth_BattleLogicState_ResolvingTurn --> Labyrinth_BattleLogicState_AwaitingCuePlayback : AdvanceResolution
Labyrinth_BattleLogicState_ResolvingTurn --> Labyrinth_BattleLogicState_SelectingCommands : AdvanceResolution
Labyrinth_BattleLogicState_SelectingCommands --> Labyrinth_BattleLogicState_ResolvingTurn : SubmitCommand
Labyrinth_BattleLogicState_SelectingCommands --> Labyrinth_BattleLogicState_SelectingCommands : SubmitCommand
Labyrinth_BattleLogicState_SelectingCommands --> Labyrinth_BattleLogicState_SelectingCommands : UndoCommand

Labyrinth_BattleLogicState : Complete() → BattleCompleted, ReturnModeRequested
Labyrinth_BattleLogicState : OutputCommandRequest() → CommandRequested
Labyrinth_BattleLogicState : Start() → BattleStarted
Labyrinth_BattleLogicState_ResolvingTurn : OnAdvanceResolution → CuePlaybackRequested
Labyrinth_BattleLogicState_SelectingCommands : OnSubmitCommand → CommandRejected
Labyrinth_BattleLogicState_SelectingCommands : OnUndoCommand → CommandUndone
@enduml